name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
    # You may pin to the exact commit or the version.
    # uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a
      uses: docker/login-action@v1.8.0
      with:
      # Server address of Docker registry. If not set then will default to Docker Hub
        registry: firstfinancial.jfrog.io          
        username: ${{ secrets.JFROGUSER }}
        password: ${{ secrets.APIKEY }}     
        uses: actions/checkout@v2
        name: Build the Docker image
        run: |
          docker build --tag firstfinancial.jfrog.io/docker/my-docker-image:latest
          docker push firstfinancial.jfrog.io/docker/my-docker-image:latest
