name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        registry: firstfinancial.jfrog.io          
        username: ${{ secrets.JFROGUSER }}
        password: ${{ secrets.APIKEY }} 
    - name: Chekout src
      uses: actions/checkout@v2
    - name: Build the Docker image
      
      run: |
        docker build . --tag firstfinancial.jfrog.io/docker/my-docker-image:latest
        docker push firstfinancial.jfrog.io/docker/my-docker-image:latest
