name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        echo "${{ secrets.APIKEY }}" | docker login firstfinancial.jfrog.io --username "${{ secrets.JFROGUSER }}" --password-stdin
        docker build --tag firstfinancial.jfrog.io/docker/my-docker-image:latest
        docker push firstfinancial.jfrog.io/docker/my-docker-image:latest
